
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int IN = 10;
  public static final int RCURLYBRACKET = 7;
  public static final int STRING_LITERAL = 3;
  public static final int PLUS = 8;
  public static final int EOF = 0;
  public static final int IF = 12;
  public static final int ELSE = 13;
  public static final int COMMA = 11;
  public static final int LCURLYBRACKET = 6;
  public static final int error = 1;
  public static final int RPAREN = 5;
  public static final int IDENTIFIER = 2;
  public static final int EQUALS = 9;
  public static final int LPAREN = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFIER",
  "STRING_LITERAL",
  "LPAREN",
  "RPAREN",
  "LCURLYBRACKET",
  "RCURLYBRACKET",
  "PLUS",
  "EQUALS",
  "IN",
  "COMMA",
  "IF",
  "ELSE"
  };
}

